version: 2
updates:
  - package-ecosystem: nuget
    directory: /assay-server
    schedule:
      interval: daily
    groups:
      osu:
        patterns:
          - "ppy.osu.Game*"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /assay-server
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
